# Generated by Django 4.2.16 on 2026-03-03 12:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('salary_from', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_to', models.PositiveIntegerField(blank=True, null=True)),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract'), ('INTERN', 'Intern')], default='FULL_TIME', max_length=20)),
                ('work_format', models.CharField(choices=[('OFFICE', 'Office'), ('REMOTE', 'Remote'), ('HYBRID', 'Hybrid')], default='OFFICE', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('requirements', models.TextField(blank=True, default='')),
                ('conditions', models.TextField(blank=True, default='')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='organizations.organization')),
            ],
            options={
                'verbose_name_plural': 'vacancies',
                'ordering': ['-created_at'],
            },
        ),
    ]
